ALTER TABLE proveedores ADD COLUMN dni_cuit VARCHAR(20) NOT NULL;
ALTER TABLE proveedores ADD COLUMN direccion VARCHAR(255);
ALTER TABLE proveedores ADD COLUMN tipo VARCHAR(50);
ALTER TABLE proveedores ADD COLUMN gremio VARCHAR(50);
ALTER TABLE proveedores ADD COLUMN activo BOOLEAN DEFAULT TRUE;
ALTER TABLE movimientos ADD COLUMN pagado BOOLEAN DEFAULT FALSE;
