version: '3.9'

services:
  proxy-server:
    build: ./proxy-server
    image: sistema-gestion-obras/proxy-server:latest
    container_name: sgo_proxy_server
    environment:
      - NODE_ENV=production
      - PORT=3000
      - TARGET_API=http://api-gateway:8080
    ports:
      - '3000:3000'
    restart: unless-stopped
    networks:
      - backend

  frontend:
    build: ./frontend1.2
    image: sistema-gestion-obras/frontend:latest
    container_name: obras_frontend
    depends_on:
      - proxy-server
    ports:
      - '4200:80'
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    external: true
    name: sgo_backend
