[build]
  functions = "netlify/functions"
  publish = "dist/sistema-gestion-obras"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/proxy/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
