spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.root=INFO
logging.level.com.agendas=DEBUG

# --- CALLMEBOT (dev local) ---
whatsapp.owner-phone=543518127383
callmebot.api-key=REEMPLAZAR_CON_TU_APIKEY
services.obras.url=http://localhost:8081
