# Production profile: keep data and skip seeding
server.port=8086
spring.application.name=transacciones-service

# Database settings are inherited from application.properties to use SQL Server
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true

# Do not run data.sql in prod
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false

# Archivo en produccion (ajustar si es necesario)
file.upload-dir=/app/uploads

# =========================
# SERVICIOS EXTERNOS
# =========================
services.obras.url=http://obras-service:8081/api/obras
