spring.config.import=optional:file:.env[.properties]
# =========================
# CONFIGURACION GENERAL
# =========================
server.port=8086
spring.application.name=transacciones-service

# =========================
# BASE DE DATOS H2 (dev)
# =========================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:transacciones;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.h2.Driver

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true

# =========================
# SQL INIT (activo)
# =========================
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data-dev.sql
spring.sql.init.continue-on-error=true
spring.sql.init.encoding=UTF-8
spring.jpa.defer-datasource-initialization=true

# =========================
# H2 Console (dev)
# =========================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# =========================
# MIGRACION SQLITE -> SQL SERVER
# =========================
app.migration.enabled=${APP_MIGRATION_ENABLED:false}
app.migration.sqlite-url=${APP_MIGRATION_SQLITE_URL:}

# =========================
# LOGGING DETALLADO
# =========================
logging.level.org.springframework.jdbc.datasource.init=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# =========================
# ERROR HANDLING
# =========================
server.error.include-message=always
server.error.include-binding-errors=always
app.migration.schema=dbo
